# Generated by Django 4.0.5 on 2022-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.CharField(default=None, max_length=100)),
                ('name', models.CharField(default=None, max_length=100)),
                ('area', models.CharField(default=None, max_length=100)),
                ('food_drink', models.CharField(default=None, max_length=100)),
                ('cuisine', models.CharField(default=None, max_length=100)),
                ('type', models.CharField(default=None, max_length=100)),
                ('contact', models.PositiveIntegerField(default=None)),
                ('location', models.CharField(default=None, max_length=100)),
                ('website', models.CharField(default=None, max_length=100)),
                ('outdoor_image', models.CharField(default=None, max_length=250)),
                ('indoor_image', models.CharField(default=None, max_length=250)),
                ('price', models.PositiveIntegerField(default=None)),
                ('google_review', models.PositiveIntegerField(default=None)),
                ('opening_times', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
