# Generated by Django 4.0.5 on 2022-06-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='google_review',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.FloatField(default=None),
        ),
    ]
