# Generated by Django 4.0.5 on 2022-06-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_alter_restaurant_google_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='area_de',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='area_fr',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_de',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_fr',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_drink_de',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='food_drink_fr',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_de',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_fr',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
