# Generated by Django 4.0.5 on 2022-06-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resort', models.CharField(default=None, max_length=50)),
                ('sub_resort', models.CharField(default=None, max_length=50)),
                ('location_car', models.CharField(default=None, max_length=250)),
                ('location_bus', models.CharField(default=None, max_length=250)),
                ('location_score', models.PositiveIntegerField(default=None)),
                ('piste', models.CharField(default=None, max_length=250)),
                ('piste_score', models.PositiveIntegerField(default=None)),
                ('off_piste', models.CharField(default=None, max_length=250)),
                ('off_piste_score', models.PositiveIntegerField(default=None)),
                ('lunch', models.CharField(default=None, max_length=250)),
                ('lunch_score', models.PositiveIntegerField(default=None)),
                ('breadth', models.CharField(default=None, max_length=250)),
                ('breadth_score', models.PositiveIntegerField(default=None)),
                ('other', models.CharField(default=None, max_length=250)),
                ('bus_route', models.PositiveIntegerField(default=None)),
                ('bus_map', models.CharField(default=None, max_length=250)),
                ('ski_map', models.CharField(default=None, max_length=250)),
                ('ski_price', models.CharField(default=None, max_length=250)),
                ('car_park', models.CharField(default=None, max_length=250)),
            ],
        ),
    ]
