# Generated by Django 4.0.5 on 2022-06-08 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain_area', models.CharField(default=None, max_length=50)),
                ('restaurant_name', models.CharField(default=None, max_length=100)),
                ('price', models.CharField(default=None, max_length=50)),
                ('lift_near', models.CharField(default=None, max_length=50)),
                ('google_review', models.FloatField(default=None)),
                ('cuisine', models.CharField(default=None, max_length=50)),
                ('size', models.CharField(default=None, max_length=50)),
                ('tips', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
