# Generated by Django 4.0.5 on 2022-06-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0003_mountain_mountain_lunch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='mountain_lunch',
            field=models.ManyToManyField(blank=True, related_name='mountains', to='mountains.lunch'),
        ),
    ]
