# Generated by Django 4.0.5 on 2022-06-16 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0006_remove_mountain_car_park_mountain_black_runs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mountain',
            name='location_car_de',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='location_car_fr',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='lunch_de',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='lunch_fr',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='off_piste_de',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='off_piste_fr',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='other_de',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='other_fr',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='piste_de',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='piste_fr',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='weather_comment_de',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='mountain',
            name='weather_comment_fr',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='mountain',
            name='piste',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
