# Generated by Django 4.0.5 on 2022-06-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default=None, max_length=50)),
                ('section', models.CharField(default=None, max_length=50)),
                ('language_id', models.PositiveIntegerField(default=None)),
                ('english', models.CharField(default=None, max_length=500, null=True)),
                ('french', models.CharField(default=None, max_length=500, null=True)),
                ('german', models.CharField(default=None, max_length=500, null=True)),
            ],
        ),
    ]
