# Generated by Django 4.0.5 on 2022-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountains', '0001_initial'),
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='mountain_detail',
            field=models.ManyToManyField(related_name='resorts', to='mountains.mountain'),
        ),
    ]
