# Generated by Django 4.0.5 on 2022-06-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('resorts', '0002_resort_mountain_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='resort_restaurants',
            field=models.ManyToManyField(related_name='resorts', to='restaurants.restaurant'),
        ),
    ]
