# Generated by Django 4.0.5 on 2022-06-09 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('mountains', '0003_mountain_mountain_lunch'),
        ('resorts', '0003_resort_resort_restaurants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='mountain_detail',
            field=models.ManyToManyField(blank=True, related_name='resorts', to='mountains.mountain'),
        ),
        migrations.AlterField(
            model_name='resort',
            name='resort_restaurants',
            field=models.ManyToManyField(blank=True, related_name='resorts', to='restaurants.restaurant'),
        ),
    ]
