# Generated by Django 4.0.5 on 2022-06-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0005_resort_resort_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='mountain_image',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
