# Generated by Django 4.0.5 on 2022-06-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0008_resort_owner_alter_resort_mountain_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='restaurant_summary',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
