# Generated by Django 4.0.5 on 2022-06-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0009_resort_restaurant_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='restaurant_summary',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
